version: '3.3'  # Use a compatible version

services:
  mysql:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    container_name: foodprint-mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - foodprint-db:/var/lib/mysql
    networks:
      - foodprint-network

volumes:
  foodprint-db:

networks:
  foodprint-network:
    driver: bridge